### ISSUE TITLE
Ocean fishing timers not functional after 7.1

### ISSUE THREAD

**Issue by xephero** [NotNite/DistantSeas#12]
The instance timer on the UI showed as 0:00 in all three zones for the full duration. When spectral hit, the spectral timers had negative values for both minutes and seconds, I believe on the second spectral it started at -38:-02 or so, and counted to -03, -04, etc. Didn't get a screenshot, sorry. Not sure it matters, but this was on the indigo route boat at 2024-11-21 06:00:00 UTC.

I assume this is upstream from all the 7.1 struct shuffling ([maybe this?](https://github.com/aers/FFXIVClientStructs/blob/958474a8f0b6dba84ba8e18be113a9b4b478ae8d/FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/InstanceContentOceanFishing.cs#L33) idk) but I don't know how to test it myself, so I'm reporting it here just in case it's with the plugin.

**Comment by NotNite** [comment]
Yeah, it's very possible I messed up - I'll have to look further into it when I have more time. Sorry!

**Comment by NotNite** [comment]
Should be fixed soon!
