### ISSUE TITLE
Spectral Wrasse wrong bait

### ISSUE THREAD

**Issue by Shuraen** [NotNite/DistantSeas#4]
As per title. Most sources (among others, Lulu's Tools specifically) point to Ragworm to catch the Spectral Wrasse, but the plugin suggests we use Krill instead.

**Comment by NotNite** [comment]
Both baits are marked as "Best" with the same bite times on the Ocean Fishing Spreadsheet:
![image](https://github.com/NotNite/DistantSeas/assets/44414597/1f84c068-a632-4f50-831b-80710579d547)
